const {
    DATABASE_URL,
    DB_DATA_STRATEGY,
    FFTBG_BASE_URL,
    FFTBG_DATA_STRATEGY,
    FORCE_TABLE_SYNC,
    PORT,
    TWITCH_USERNAME,
    TWITCH_AUTH_TOKEN,
} = process.env;

module.exports = {
    DATABASE_URL,
    DB_DATA_STRATEGY,
    FFTBG_BASE_URL,
    FFTBG_DATA_STRATEGY,
    FORCE_TABLE_SYNC,
    PORT,
    TWITCH_USERNAME,
    TWITCH_AUTH_TOKEN,
}